pub(crate) mod camera;
pub(crate) mod cleanup;
pub(crate) mod consumption;
pub(crate) mod logging;
pub(crate) mod movement;
pub(crate) mod renderer;
pub(crate) mod spawner;
pub(crate) mod specialization_transformer;
pub(crate) mod ui;
